controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml

login:
    path: /login
    controller: App\Contoller\SecurityController::login

